<div class="entry-edit">
    <form method="post" action="/admin/oneClick/cancel/">
        <input type="hidden" name="id" value="<?php echo $this->getOneClickOrderId(); ?>">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">Cancel order</h4>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                    <tr>
                        <td class="label"><label for="product_price">Comment</label></td>
                        <td class="value">
                            <textarea name="comment" cols="15" rows="2"></textarea>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <button type="submit" class="scalable save" style="">
            <span>
                <span>
                    <span>Save</span>
                </span>
            </span>
        </button>
    </form>
</div>