<?php if (!$this->isLogged()):?>
    <div class="modal fade" tabindex="-1" role="dialog" name="infoModalWindow">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Information</h4>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal js-oneClickOrder-from" action="/oneclick/index/save/">
                        <input type="hidden" name="product_id" value="<?php echo Mage::registry('current_product')->getId(); ?>">
                        <div class="form-group">
                            <label for="username" class="col-sm-2 control-label">Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="username" id="username" placeholder="name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="userPhone" class="col-sm-2 control-label">Phone</label>
                            <div class="col-sm-10">
                                <input type="tel" class="form-control" name="phone" id="userPhone" placeholder="Phone">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary js-order-form-submit">Buy!</button>
                </div>
            </div>
        </div>
    </div>
<?php endif;?>
